//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvaluacionVehiculosMVC.WSEvaluacionInacap {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserAccount", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class UserAccount : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserAlumnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IsValudOrMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UserAlumno {
            get {
                return this.UserAlumnoField;
            }
            set {
                if ((object.ReferenceEquals(this.UserAlumnoField, value) != true)) {
                    this.UserAlumnoField = value;
                    this.RaisePropertyChanged("UserAlumno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string UserCode {
            get {
                return this.UserCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.UserCodeField, value) != true)) {
                    this.UserCodeField = value;
                    this.RaisePropertyChanged("UserCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string IsValudOrMessage {
            get {
                return this.IsValudOrMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.IsValudOrMessageField, value) != true)) {
                    this.IsValudOrMessageField = value;
                    this.RaisePropertyChanged("IsValudOrMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UFValue", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class UFValue : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UFDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UFValuesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IsValudOrMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UFDate {
            get {
                return this.UFDateField;
            }
            set {
                if ((object.ReferenceEquals(this.UFDateField, value) != true)) {
                    this.UFDateField = value;
                    this.RaisePropertyChanged("UFDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UFValues {
            get {
                return this.UFValuesField;
            }
            set {
                if ((object.ReferenceEquals(this.UFValuesField, value) != true)) {
                    this.UFValuesField = value;
                    this.RaisePropertyChanged("UFValues");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string IsValudOrMessage {
            get {
                return this.IsValudOrMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.IsValudOrMessageField, value) != true)) {
                    this.IsValudOrMessageField = value;
                    this.RaisePropertyChanged("IsValudOrMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LogUseResult", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class LogUseResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LogStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LogMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string LogStatus {
            get {
                return this.LogStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.LogStatusField, value) != true)) {
                    this.LogStatusField = value;
                    this.RaisePropertyChanged("LogStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string LogMessage {
            get {
                return this.LogMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.LogMessageField, value) != true)) {
                    this.LogMessageField = value;
                    this.RaisePropertyChanged("LogMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSEvaluacionInacap.WSEvaluacionInacapSoap")]
    public interface WSEvaluacionInacapSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento TestConexionResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TestConexion", ReplyAction="*")]
        EvaluacionVehiculosMVC.WSEvaluacionInacap.TestConexionResponse TestConexion(EvaluacionVehiculosMVC.WSEvaluacionInacap.TestConexionRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento userAlumno del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        EvaluacionVehiculosMVC.WSEvaluacionInacap.LoginResponse Login(EvaluacionVehiculosMVC.WSEvaluacionInacap.LoginRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento dateOfUF del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUFValue", ReplyAction="*")]
        EvaluacionVehiculosMVC.WSEvaluacionInacap.GetUFValueResponse GetUFValue(EvaluacionVehiculosMVC.WSEvaluacionInacap.GetUFValueRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento userCode del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoggedPurchase", ReplyAction="*")]
        EvaluacionVehiculosMVC.WSEvaluacionInacap.LoggedPurchaseResponse LoggedPurchase(EvaluacionVehiculosMVC.WSEvaluacionInacap.LoggedPurchaseRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestConexionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestConexion", Namespace="http://tempuri.org/", Order=0)]
        public EvaluacionVehiculosMVC.WSEvaluacionInacap.TestConexionRequestBody Body;
        
        public TestConexionRequest() {
        }
        
        public TestConexionRequest(EvaluacionVehiculosMVC.WSEvaluacionInacap.TestConexionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TestConexionRequestBody {
        
        public TestConexionRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestConexionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestConexionResponse", Namespace="http://tempuri.org/", Order=0)]
        public EvaluacionVehiculosMVC.WSEvaluacionInacap.TestConexionResponseBody Body;
        
        public TestConexionResponse() {
        }
        
        public TestConexionResponse(EvaluacionVehiculosMVC.WSEvaluacionInacap.TestConexionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TestConexionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TestConexionResult;
        
        public TestConexionResponseBody() {
        }
        
        public TestConexionResponseBody(string TestConexionResult) {
            this.TestConexionResult = TestConexionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://tempuri.org/", Order=0)]
        public EvaluacionVehiculosMVC.WSEvaluacionInacap.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(EvaluacionVehiculosMVC.WSEvaluacionInacap.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userAlumno;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string passwordAlumno;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string userAlumno, string passwordAlumno) {
            this.userAlumno = userAlumno;
            this.passwordAlumno = passwordAlumno;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public EvaluacionVehiculosMVC.WSEvaluacionInacap.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(EvaluacionVehiculosMVC.WSEvaluacionInacap.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public EvaluacionVehiculosMVC.WSEvaluacionInacap.UserAccount LoginResult;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(EvaluacionVehiculosMVC.WSEvaluacionInacap.UserAccount LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUFValueRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUFValue", Namespace="http://tempuri.org/", Order=0)]
        public EvaluacionVehiculosMVC.WSEvaluacionInacap.GetUFValueRequestBody Body;
        
        public GetUFValueRequest() {
        }
        
        public GetUFValueRequest(EvaluacionVehiculosMVC.WSEvaluacionInacap.GetUFValueRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUFValueRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string dateOfUF;
        
        public GetUFValueRequestBody() {
        }
        
        public GetUFValueRequestBody(string dateOfUF) {
            this.dateOfUF = dateOfUF;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUFValueResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUFValueResponse", Namespace="http://tempuri.org/", Order=0)]
        public EvaluacionVehiculosMVC.WSEvaluacionInacap.GetUFValueResponseBody Body;
        
        public GetUFValueResponse() {
        }
        
        public GetUFValueResponse(EvaluacionVehiculosMVC.WSEvaluacionInacap.GetUFValueResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUFValueResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public EvaluacionVehiculosMVC.WSEvaluacionInacap.UFValue GetUFValueResult;
        
        public GetUFValueResponseBody() {
        }
        
        public GetUFValueResponseBody(EvaluacionVehiculosMVC.WSEvaluacionInacap.UFValue GetUFValueResult) {
            this.GetUFValueResult = GetUFValueResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoggedPurchaseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoggedPurchase", Namespace="http://tempuri.org/", Order=0)]
        public EvaluacionVehiculosMVC.WSEvaluacionInacap.LoggedPurchaseRequestBody Body;
        
        public LoggedPurchaseRequest() {
        }
        
        public LoggedPurchaseRequest(EvaluacionVehiculosMVC.WSEvaluacionInacap.LoggedPurchaseRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoggedPurchaseRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string purchaseMessage;
        
        public LoggedPurchaseRequestBody() {
        }
        
        public LoggedPurchaseRequestBody(string userCode, string purchaseMessage) {
            this.userCode = userCode;
            this.purchaseMessage = purchaseMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoggedPurchaseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoggedPurchaseResponse", Namespace="http://tempuri.org/", Order=0)]
        public EvaluacionVehiculosMVC.WSEvaluacionInacap.LoggedPurchaseResponseBody Body;
        
        public LoggedPurchaseResponse() {
        }
        
        public LoggedPurchaseResponse(EvaluacionVehiculosMVC.WSEvaluacionInacap.LoggedPurchaseResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoggedPurchaseResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public EvaluacionVehiculosMVC.WSEvaluacionInacap.LogUseResult LoggedPurchaseResult;
        
        public LoggedPurchaseResponseBody() {
        }
        
        public LoggedPurchaseResponseBody(EvaluacionVehiculosMVC.WSEvaluacionInacap.LogUseResult LoggedPurchaseResult) {
            this.LoggedPurchaseResult = LoggedPurchaseResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSEvaluacionInacapSoapChannel : EvaluacionVehiculosMVC.WSEvaluacionInacap.WSEvaluacionInacapSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSEvaluacionInacapSoapClient : System.ServiceModel.ClientBase<EvaluacionVehiculosMVC.WSEvaluacionInacap.WSEvaluacionInacapSoap>, EvaluacionVehiculosMVC.WSEvaluacionInacap.WSEvaluacionInacapSoap {
        
        public WSEvaluacionInacapSoapClient() {
        }
        
        public WSEvaluacionInacapSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSEvaluacionInacapSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSEvaluacionInacapSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSEvaluacionInacapSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EvaluacionVehiculosMVC.WSEvaluacionInacap.TestConexionResponse EvaluacionVehiculosMVC.WSEvaluacionInacap.WSEvaluacionInacapSoap.TestConexion(EvaluacionVehiculosMVC.WSEvaluacionInacap.TestConexionRequest request) {
            return base.Channel.TestConexion(request);
        }
        
        public string TestConexion() {
            EvaluacionVehiculosMVC.WSEvaluacionInacap.TestConexionRequest inValue = new EvaluacionVehiculosMVC.WSEvaluacionInacap.TestConexionRequest();
            inValue.Body = new EvaluacionVehiculosMVC.WSEvaluacionInacap.TestConexionRequestBody();
            EvaluacionVehiculosMVC.WSEvaluacionInacap.TestConexionResponse retVal = ((EvaluacionVehiculosMVC.WSEvaluacionInacap.WSEvaluacionInacapSoap)(this)).TestConexion(inValue);
            return retVal.Body.TestConexionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EvaluacionVehiculosMVC.WSEvaluacionInacap.LoginResponse EvaluacionVehiculosMVC.WSEvaluacionInacap.WSEvaluacionInacapSoap.Login(EvaluacionVehiculosMVC.WSEvaluacionInacap.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public EvaluacionVehiculosMVC.WSEvaluacionInacap.UserAccount Login(string userAlumno, string passwordAlumno) {
            EvaluacionVehiculosMVC.WSEvaluacionInacap.LoginRequest inValue = new EvaluacionVehiculosMVC.WSEvaluacionInacap.LoginRequest();
            inValue.Body = new EvaluacionVehiculosMVC.WSEvaluacionInacap.LoginRequestBody();
            inValue.Body.userAlumno = userAlumno;
            inValue.Body.passwordAlumno = passwordAlumno;
            EvaluacionVehiculosMVC.WSEvaluacionInacap.LoginResponse retVal = ((EvaluacionVehiculosMVC.WSEvaluacionInacap.WSEvaluacionInacapSoap)(this)).Login(inValue);
            return retVal.Body.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EvaluacionVehiculosMVC.WSEvaluacionInacap.GetUFValueResponse EvaluacionVehiculosMVC.WSEvaluacionInacap.WSEvaluacionInacapSoap.GetUFValue(EvaluacionVehiculosMVC.WSEvaluacionInacap.GetUFValueRequest request) {
            return base.Channel.GetUFValue(request);
        }
        
        public EvaluacionVehiculosMVC.WSEvaluacionInacap.UFValue GetUFValue(string dateOfUF) {
            EvaluacionVehiculosMVC.WSEvaluacionInacap.GetUFValueRequest inValue = new EvaluacionVehiculosMVC.WSEvaluacionInacap.GetUFValueRequest();
            inValue.Body = new EvaluacionVehiculosMVC.WSEvaluacionInacap.GetUFValueRequestBody();
            inValue.Body.dateOfUF = dateOfUF;
            EvaluacionVehiculosMVC.WSEvaluacionInacap.GetUFValueResponse retVal = ((EvaluacionVehiculosMVC.WSEvaluacionInacap.WSEvaluacionInacapSoap)(this)).GetUFValue(inValue);
            return retVal.Body.GetUFValueResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EvaluacionVehiculosMVC.WSEvaluacionInacap.LoggedPurchaseResponse EvaluacionVehiculosMVC.WSEvaluacionInacap.WSEvaluacionInacapSoap.LoggedPurchase(EvaluacionVehiculosMVC.WSEvaluacionInacap.LoggedPurchaseRequest request) {
            return base.Channel.LoggedPurchase(request);
        }
        
        public EvaluacionVehiculosMVC.WSEvaluacionInacap.LogUseResult LoggedPurchase(string userCode, string purchaseMessage) {
            EvaluacionVehiculosMVC.WSEvaluacionInacap.LoggedPurchaseRequest inValue = new EvaluacionVehiculosMVC.WSEvaluacionInacap.LoggedPurchaseRequest();
            inValue.Body = new EvaluacionVehiculosMVC.WSEvaluacionInacap.LoggedPurchaseRequestBody();
            inValue.Body.userCode = userCode;
            inValue.Body.purchaseMessage = purchaseMessage;
            EvaluacionVehiculosMVC.WSEvaluacionInacap.LoggedPurchaseResponse retVal = ((EvaluacionVehiculosMVC.WSEvaluacionInacap.WSEvaluacionInacapSoap)(this)).LoggedPurchase(inValue);
            return retVal.Body.LoggedPurchaseResult;
        }
    }
}
